name: publish-branch
on:
  workflow_dispatch:
  push:
jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ACTION_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.11.1
          registry-url: https://npm.pkg.github.com

      - name: Git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ env.ACTION_GITHUB_TOKEN }}

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: BRANCHNAME
        run: echo none BRANCH_NAME && echo dollar $BRANCH_NAME
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: head ref
        run: echo ${{ github.head_ref }}

      - name: sha
        run: ${{ github.sha }}
