name: publish-branch
on:
  workflow_dispatch:
  push:
jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ACTION_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      GITHUB_SHA_SHORT: $(echo $GITHUB_SHA | cut -c1-7)

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.11.1
          registry-url: https://npm.pkg.github.com

      - name: Git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ env.ACTION_GITHUB_TOKEN }}

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: info
        run: |
          echo $BRANCH_NAME
          echo running on branch ${GITHUB_REF##*/}
          echo sha: $GITHUB_SHA_SHORT

      # - name: Set version
      #   run: |
      #     npm version prerelease --preid=$BRANCH_NAME

      # - name: Get package version
      #   id: package-version
      #   uses: martinbeentjes/npm-get-version-action@master

      # - name: Package info
      #   run: echo package version ${{ steps.package-version.outputs.current-version }}

      # - name: Publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     npm publish --tag $BRANCH_NAME
